### ISSUE TITLE
Use in other locations

### ISSUE THREAD

**Issue by ngovil21** [xiankai/sg-pokemongo-ex-raid-map#4]
Hey this map is exactly what I was looking for to plan EX-Raids in my city. Is it okay for me to use the code for personal use and would you be willing to give an explanation on how to set it up for a different location?

**Comment by xiankai** [comment]
Hey, I don't mind you using the map as it is, as long there is a small attribution at the bottom to the original map.

However as the bulk of the work required actually lies in generating and setting up the datasets, that is a level of explanation that I am not yet ready to prepare for.

In the meantime however I shall be working on a simple readme document to at least explain the basic features/layout of the site.

**Comment by xiankai** [comment]
I have included instructions in the README now on how to set up a similar site, along with the data format I use. As mentioned earlier, how you get the data is up to you. Hope that helps!
