### ISSUE TITLE
Overlay with SGPokemap raid data?

### ISSUE THREAD

**Issue by wasabigeek** [xiankai/sg-pokemongo-ex-raid-map#7]
What do you think of overlaying "live" raid data? So people can immediately tell which current raids are in a potential ex-raid gym.

I don't know the SGPokemap dev personally though, so not sure how he'd respond to it.

**Comment by xiankai** [comment]
I would also like to do this, but it would also be costly in terms of providing a backend service, and I do not want to leech off others' server's resources (given the amount of visitors that would put a strain on their server load that already requires donations)

**Comment by wasabigeek** [comment]
That's true. What about something like this:
- a cron once every 15 minutes (since eggs pop up an hour before this should be ample time, while limiting load on sgpokemap to 4 requests per hour)
- removing the Google maps link and instead link to the raid on sgpokemap so the creators at least get some advertising revenue

Of course should definitely reach out to the creators. Maybe they'll offer to do it the other way round even? Haha. Would be happy to try and ask if you're open, and can maybe contribute a little code.
